# Generated by Django 5.1 on 2024-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='colour',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.TextField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='size',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
