# Generated by Django 5.1 on 2024-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_customer_address_customer_colour_customer_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
