# Generated by Django 5.1 on 2024-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_customer_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
