# Generated by Django 5.1 on 2024-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_alter_customer_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
