# Generated by Django 5.1 on 2024-09-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_customer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
