# Generated by Django 5.1 on 2024-09-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_rename_product_id_customer_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_name',
        ),
    ]
