# Generated by Django 5.1 on 2024-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_remove_customer_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
