# Generated by Django 5.1 on 2024-09-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_customer_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
